#!/bin/bash

echo "🚀 No-Dues Application Deployment Guide"
echo ""

echo "📋 Deployment Steps:"
echo ""
echo "1. Backend (Railway):"
echo "   - Push code to GitHub"
echo "   - Connect Railway to your GitHub repo"
echo "   - Set environment variables in Railway dashboard"
echo "   - Deploy automatically"
echo ""
echo "2. Frontend (Vercel):"
echo "   - Import frontend folder to Vercel"
echo "   - Set root directory to 'frontend'"
echo "   - Set REACT_APP_API_URL environment variable"
echo "   - Deploy"
echo ""
echo "3. Environment Variables to set:"
echo ""
echo "   Backend (Railway):"
echo "   - MONGODB_URI"
echo "   - JWT_SECRET"
echo "   - NODE_ENV=production"
echo "   - FRONTEND_URL"
echo ""
echo "   Frontend (Vercel):"
echo "   - REACT_APP_API_URL (your Railway backend URL)"
echo ""
echo "📖 See DEPLOYMENT.md for detailed instructions"
