services:
  - type: web
    name: no-dues-app
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    rootDir: .
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
